### PR TITLE
add client to abstract solve requests

### PR DESCRIPTION
**Pull request by lixitrixi**
Here I add a basic front-end client to abstract the process of sending Essence to the API. Its main use is to turn the process of repeatedly polling the `get` endpoint until it returns something other than `"wait"` into a Promise.

### CODE REVIEW

**Review by ozgurakgun — APPROVED** [review]

**Comment by lixitrixi** [comment]
Two quick things:

1. What are all the strings that are valid for the solver? Is it the same as those in the Makefile for Conjure? I.e:
```
"bc_minisat_all"|"boolector"|"cadical"|"chuffed"|"gecode"|"glucose"|"kissat"|"lingeling"|"minion"|"nbc_minisat_all"|"open"|"ortools"|"yices"|"z3"
```

2. What is the minimum time that Conjure could take to solve a problem (for the first poll)? And what is a good cooldown between polls?

**Comment by ozgurakgun** [comment]
Can you also add an example of using this? Maybe create a copy of [submitDemo.html](https://github.com/conjure-cp/conjure-aas/blob/main/static/submitDemo.html) that uses polling and updates a status/solution div?

**Comment by ozgurakgun** [comment]
> 1. What are all the strings that are valid for the solver? Is it the same as those in the Makefile for Conjure? I.e:
> 
> 
> ```
> "bc_minisat_all"|"boolector"|"cadical"|"chuffed"|"gecode"|"glucose"|"kissat"|"lingeling"|"minion"|"nbc_minisat_all"|"open"|"ortools"|"yices"|"z3"
> ```

instead of making a full list, let's link to the docs: https://conjure.readthedocs.io/en/latest/features.html#multiple-target-solvers

>     What is the minimum time that Conjure could take to solve a problem (for the first poll)? And what is a good cooldown between polls?

Hard to know, but waiting 1 sec is probably a good idea.

Regarding cooldown, we could either do every n seconds (which could be a parameter to your abstraction?) or something like a luby sequence 

See: https://choco-solver.org/docs/solving/restarts/#luby

Paper: https://www.sciencedirect.com/science/article/abs/pii/0020019093900299

Code: https://www.dcs.gla.ac.uk/~pat/maxClique/distribution/java-201810/Luby.java

**Comment by lixitrixi** [comment]
I've tried my hand at the Luby sequence but will need some time to figure it out haha

I've put the client file in the actually correct place after testing. This should now work in production @ozgurakgun

**Comment by ozgurakgun** [comment]
thanks! let me know if you want to do luby, the java code I linked to should be portable.

**Pull request merged**
