### PR TITLE
Tweak solve demo page

### PR DESCRIPTION
**Pull request by lixitrixi**
Here I make some slight visual and layout improvements to the solve demo page using some basic Bootstrap and JQuery.

image

(Yes, I am taking a break from normal software engineering by doing web design)

### CODE REVIEW

**Comment by ozgurakgun** [comment]
I quite like the current one column layout if I'm honest :)

https://conjure-aas.cs.st-andrews.ac.uk/solveDemo.html

Some of the details (like the horizontal line, button colour and rewording of the labels) are good, but I am not a fan of having less width for the model.

On the other hand this is just a demo and we are both probably spending too much time on this already...

**Comment by lixitrixi** [comment]
@ozgurakgun heard! I changed that really quick.

Very fair, but I've been doing so much hard programming that I need something visual or I will go insane

**Comment by lixitrixi** [comment]
I'm all done now :)

My next contributions will be the rule constraint/variable updating system!

**Comment by ozgurakgun** [comment]
> My next contributions will be the rule constraint/variable updating system!

but in JS?

**Pull request merged**
